# Generated by Django 3.1.1 on 2020-09-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr',
            field=models.CharField(max_length=99),
        ),
    ]
