# Generated by Django 3.1.1 on 2020-09-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200918_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr',
            field=models.CharField(max_length=999),
        ),
    ]
